In [1]:
#import library and ignore warning
import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [2]:
#laod dataset
data_preprocessed = pd.read_csv('../data/preprocessed/clean_Absenteeism_data.csv')

In [3]:
data_preprocessed.head()

,reason_1,reason_2,reason_3,reason_4,transportation_expense,distance_to_work,age,daily_work_load_average,body_mass_index,education,children,pets,absenteeism_time_in_hours,month_value,day_of_the_week
0,0,0,0,1,289,36,33,239.554,30,0,2,1,4,7,1
1,0,0,0,0,118,13,50,239.554,31,0,1,0,0,7,1
2,0,0,0,1,179,51,38,239.554,31,0,0,0,2,7,2
3,1,0,0,0,279,5,39,239.554,24,0,2,0,4,7,3
4,0,0,0,1,289,36,33,239.554,30,0,2,1,2,7,3


In [4]:
#create target
data_preprocessed['absenteeism_time_in_hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['absenteeism_time_in_hours'] >
                   data_preprocessed['absenteeism_time_in_hours'].median(), 1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [6]:
data_preprocessed['excessive_absenteeism'] = targets
data_preprocessed.head()

,reason_1,reason_2,reason_3,reason_4,transportation_expense,distance_to_work,age,daily_work_load_average,body_mass_index,education,children,pets,absenteeism_time_in_hours,month_value,day_of_the_week,excessive_absenteeism
0,0,0,0,1,289,36,33,239.554,30,0,2,1,4,7,1,1
1,0,0,0,0,118,13,50,239.554,31,0,1,0,0,7,1,0
2,0,0,0,1,179,51,38,239.554,31,0,0,0,2,7,2,0
3,1,0,0,0,279,5,39,239.554,24,0,2,0,4,7,3,1
4,0,0,0,1,289,36,33,239.554,30,0,2,1,2,7,3,0


In [7]:
targets.sum() / targets.shape[0]

np.float64(0.45571428571428574)

In [8]:
data_with_targets = data_preprocessed.drop(['absenteeism_time_in_hours', 'day_of_the_week', 
                                            'distance_to_work', 'daily_work_load_average' ], axis=1)

In [9]:
#check if it the same
data_with_targets is data_preprocessed

False

In [10]:
data_with_targets.head()

,reason_1,reason_2,reason_3,reason_4,transportation_expense,age,body_mass_index,education,children,pets,month_value,excessive_absenteeism
0,0,0,0,1,289,33,30,0,2,1,7,1
1,0,0,0,0,118,50,31,0,1,0,7,0
2,0,0,0,1,179,38,31,0,0,0,7,0
3,1,0,0,0,279,39,24,0,2,0,7,1
4,0,0,0,1,289,33,30,0,2,1,7,0


In [11]:
#select the inputs for the regression
data_with_targets.shape

(700, 12)

In [12]:
data_with_targets.iloc[:, :-1]

,reason_1,reason_2,reason_3,reason_4,transportation_expense,age,body_mass_index,education,children,pets,month_value
0,0,0,0,1,289,33,30,0,2,1,7
1,0,0,0,0,118,50,31,0,1,0,7
2,0,0,0,1,179,38,31,0,0,0,7
3,1,0,0,0,279,39,24,0,2,0,7
4,0,0,0,1,289,33,30,0,2,1,7
...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,179,40,22,1,2,0,5
696,1,0,0,0,225,28,24,0,1,2,5
697,1,0,0,0,330,28,25,1,0,0,5
698,0,0,0,1,235,32,25,1,0,0,5


In [13]:
unscaled_inputs = data_with_targets.iloc[:, :-1]

In [14]:
#Standardize the data
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import StandardScaler

class CustomScaler(BaseEstimator, TransformerMixin):
    def __init__(self, columns, copy=True, with_mean=True, with_std=True):
        self.columns = columns
        self.copy = copy
        self.with_mean = with_mean
        self.with_std = with_std
        self.scaler = StandardScaler(copy=copy, with_mean=with_mean, with_std=with_std)
        self.mean_ = None
        self.var_ = None

    def fit(self, X, y=None):
        self.scaler.fit(X[self.columns], y)
        self.mean_ = np.mean(X[self.columns])
        self.var_ = np.var(X[self.columns])
        return self

    def transform(self, X, y=None, copy=None):
        init_col_order = X.columns
        X_scaled = pd.DataFrame(self.scaler.transform(X[self.columns]), columns=self.columns)
        X_not_scaled = X.loc[:, ~X.columns.isin(self.columns)]
        return pd.concat([X_not_scaled, X_scaled], axis=1)[init_col_order]




        
#scalar = StandardScaler()

In [15]:
unscaled_inputs.columns.values

array(['reason_1', 'reason_2', 'reason_3', 'reason_4',
       'transportation_expense', 'age', 'body_mass_index', 'education',
       'children', 'pets', 'month_value'], dtype=object)

In [16]:
#do not scale the reason_1-3 aaand education as it dummie

#columns_to_scale = ['transportation_expense', 'distance_to_work', 'age',
       #'daily_work_load_average', 'body_mass_index',
       #'children', 'pets', 'month_value', 'day_of_the_week']

columns_to_omit = ['reason_1', 'reason_2', 'reason_3', 'reason_4', 'education' ]

In [17]:
columns_to_scale = [x for x in unscaled_inputs.columns.values if x not in columns_to_omit]

In [18]:
#apply function to scale only needed columns
scalar = CustomScaler(columns_to_scale)

In [19]:
scalar.fit(unscaled_inputs)

,columns,"['transportation_expense', 'age', ...]"
,copy,True
,with_mean,True
,with_std,True


In [20]:
# .tranform() dose the actual scaling
scaled_inputs = scalar.transform(unscaled_inputs)

In [21]:
scaled_inputs

,reason_1,reason_2,reason_3,reason_4,transportation_expense,age,body_mass_index,education,children,pets,month_value
0,0,0,0,1,1.005844,-0.536062,0.767431,0,0.880469,0.268487,0.182726
1,0,0,0,0,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690,0.182726
2,0,0,0,1,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690,0.182726
3,1,0,0,0,0.854936,0.405184,-0.643782,0,0.880469,-0.589690,0.182726
4,0,0,0,1,1.005844,-0.536062,0.767431,0,0.880469,0.268487,0.182726
...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690,-0.388293
696,1,0,0,0,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663,-0.388293
697,1,0,0,0,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690,-0.388293
698,0,0,0,1,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690,-0.388293


In [22]:
scaled_inputs.describe().round(2)

,reason_1,reason_2,reason_3,reason_4,transportation_expense,age,body_mass_index,education,children,pets,month_value
count,700.00,700.00,700.00,700.00,700.00,700.00,700.00,700.00,700.00,700.00,700.00
mean,0.25,0.01,0.09,0.60,-0.00,0.00,0.00,0.17,0.00,-0.00,-0.00
std,0.43,0.09,0.29,0.49,1.00,1.00,1.00,0.37,1.00,1.00,1.00
min,0.00,0.00,0.00,0.00,-1.57,-1.48,-1.82,0.00,-0.92,-0.59,-1.53
25%,0.00,0.00,0.00,0.00,-0.65,-0.85,-0.64,0.00,-0.92,-0.59,-0.96
50%,0.00,0.00,0.00,1.00,0.04,0.09,-0.41,0.00,-0.02,-0.59,-0.10
75%,0.25,0.00,0.00,1.00,0.57,0.56,1.00,0.00,0.88,0.27,1.04
max,1.00,1.00,1.00,1.00,2.50,3.39,2.65,1.00,2.68,6.28,1.61


In [23]:
scaled_inputs.shape

(700, 11)

In [24]:
#split the data into training and testing 
from sklearn.model_selection import train_test_split

In [25]:
train_test_split(scaled_inputs, targets)

[     reason_1  reason_2  reason_3  reason_4  transportation_expense       age  \
 590         0         0         0         1               -0.654143  0.248310   
 185         0         0         0         1                0.040034 -1.320435   
 326         0         0         1         0                0.190942  0.091435   
 79          0         0         0         1                0.568211 -0.065439   
 256         1         0         0         0                1.171843  1.032682   
 ..        ...       ...       ...       ...                     ...       ...   
 275         0         0         0         1                1.036026  0.562059   
 285         0         0         0         0                0.190942  1.032682   
 393         0         0         0         1                0.568211 -0.065439   
 298         0         0         0         1               -0.654143  0.248310   
 348         0         0         0         1               -0.654143 -1.006686   
 
      body_mas

In [26]:
#in defualt it 3-1
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets,
                                                   train_size=0.8, random_state=42)

In [27]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)


In [28]:
#logistic regression with sklearn
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [29]:
reg = LogisticRegression()

In [30]:
reg.fit(x_train, y_train)

,penalty,'l2'
,dual,False
,tol,0.0001
,C,1.0
,fit_intercept,True
,intercept_scaling,1
,class_weight,None
,random_state,None
,solver,'lbfgs'
,max_iter,100
,multi_class,'deprecated'


In [31]:
reg.score(x_train, y_train)

0.7732142857142857

In [32]:
#manually check the accuracy 
model_outputs = reg.predict(x_train)
model_outputs

array([1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,

In [33]:
y_train

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,

In [34]:
model_outputs == y_train

array([ True,  True,  True,  True, False, False, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False,  True, False,  True,
        True, False, False,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True, False, False,  True,
        True,  True, False,  True,  True, False,  True,  True,  True,
        True,  True, False,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [35]:
np.sum(model_outputs == y_train)

np.int64(433)

In [36]:
model_outputs.shape[0]

560

In [37]:
np.sum(model_outputs == y_train) / model_outputs.shape[0]

np.float64(0.7732142857142857)

In [38]:
#finding the intercept and coefficient 
reg.intercept_
#like the initial values

array([-1.70293007])

In [39]:
reg.coef_
#the x of each features

array([[ 2.9136209 ,  0.75484748,  3.09891742,  0.96486444,  0.65018629,
        -0.25112372,  0.25250206, -0.24004052,  0.39910996, -0.29389223,
         0.07441017]])

In [40]:
scaled_inputs

,reason_1,reason_2,reason_3,reason_4,transportation_expense,age,body_mass_index,education,children,pets,month_value
0,0,0,0,1,1.005844,-0.536062,0.767431,0,0.880469,0.268487,0.182726
1,0,0,0,0,-1.574681,2.130803,1.002633,0,-0.019280,-0.589690,0.182726
2,0,0,0,1,-0.654143,0.248310,1.002633,0,-0.919030,-0.589690,0.182726
3,1,0,0,0,0.854936,0.405184,-0.643782,0,0.880469,-0.589690,0.182726
4,0,0,0,1,1.005844,-0.536062,0.767431,0,0.880469,0.268487,0.182726
...,...,...,...,...,...,...,...,...,...,...,...
695,1,0,0,0,-0.654143,0.562059,-1.114186,1,0.880469,-0.589690,-0.388293
696,1,0,0,0,0.040034,-1.320435,-0.643782,0,-0.019280,1.126663,-0.388293
697,1,0,0,0,1.624567,-1.320435,-0.408580,1,-0.919030,-0.589690,-0.388293
698,0,0,0,1,0.190942,-0.692937,-0.408580,1,-0.919030,-0.589690,-0.388293


In [41]:
#get the features name
feature_name = unscaled_inputs.columns.values

In [42]:
summary_table = pd.DataFrame(columns=['feature_name'], data=feature_name)
summary_table

,feature_name
0,reason_1
1,reason_2
2,reason_3
3,reason_4
4,transportation_expense
5,age
6,body_mass_index
7,education
8,children
9,pets


In [43]:
#put the data as a columns
summary_table['coefficient'] = np.transpose(reg.coef_)
summary_table

,feature_name,coefficient
0,reason_1,2.913621
1,reason_2,0.754847
2,reason_3,3.098917
3,reason_4,0.964864
4,transportation_expense,0.650186
5,age,-0.251124
6,body_mass_index,0.252502
7,education,-0.240041
8,children,0.399110
9,pets,-0.293892


In [44]:
summary_table.index = summary_table.index + 1
summary_table

,feature_name,coefficient
1,reason_1,2.913621
2,reason_2,0.754847
3,reason_3,3.098917
4,reason_4,0.964864
5,transportation_expense,0.650186
6,age,-0.251124
7,body_mass_index,0.252502
8,education,-0.240041
9,children,0.399110
10,pets,-0.293892


In [45]:
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table

,feature_name,coefficient
1,reason_1,2.913621
2,reason_2,0.754847
3,reason_3,3.098917
4,reason_4,0.964864
5,transportation_expense,0.650186
6,age,-0.251124
7,body_mass_index,0.252502
8,education,-0.240041
9,children,0.399110
10,pets,-0.293892


In [46]:
summary_table = summary_table.sort_index()
summary_table

,feature_name,coefficient
0,Intercept,-1.702930
1,reason_1,2.913621
2,reason_2,0.754847
3,reason_3,3.098917
4,reason_4,0.964864
5,transportation_expense,0.650186
6,age,-0.251124
7,body_mass_index,0.252502
8,education,-0.240041
9,children,0.399110


In [47]:
summary_table['coefficient'] = pd.to_numeric(summary_table['coefficient'])
summary_table.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12 entries, 0 to 11
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   feature_name  12 non-null     object 
 1   coefficient   12 non-null     float64
dtypes: float64(1), object(1)
memory usage: 288.0+ bytes


In [48]:
#interpreting the coefficient
summary_table['odds_ratio'] = np.exp(summary_table.coefficient)

In [49]:
summary_table.sort_values('odds_ratio', ascending=False)

,feature_name,coefficient,odds_ratio
3,reason_3,3.098917,22.173933
1,reason_1,2.913621,18.423387
4,reason_4,0.964864,2.624432
2,reason_2,0.754847,2.127287
5,transportation_expense,0.650186,1.915898
9,children,0.399110,1.490498
7,body_mass_index,0.252502,1.287242
11,month_value,0.074410,1.077249
8,education,-0.240041,0.786596
6,age,-0.251124,0.777926


In [51]:
#backward elimination
#reduce some features that nearly to 0

In [52]:
#testing the model
reg.score(x_test, y_test)

0.7714285714285715

In [56]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba
#first columns represent 0 and last is 1

array([[0.82957126, 0.17042874],
       [0.85163998, 0.14836002],
       [0.79779583, 0.20220417],
       [0.593212  , 0.406788  ],
       [0.57365867, 0.42634133],
       [0.08041824, 0.91958176],
       [0.67595129, 0.32404871],
       [0.35568421, 0.64431579],
       [0.7163203 , 0.2836797 ],
       [0.74005176, 0.25994824],
       [0.86456635, 0.13543365],
       [0.67492732, 0.32507268],
       [0.26570587, 0.73429413],
       [0.44925745, 0.55074255],
       [0.72600362, 0.27399638],
       [0.4921817 , 0.5078183 ],
       [0.89459595, 0.10540405],
       [0.21441612, 0.78558388],
       [0.86703473, 0.13296527],
       [0.58401659, 0.41598341],
       [0.73026575, 0.26973425],
       [0.74411785, 0.25588215],
       [0.68178599, 0.31821401],
       [0.67957102, 0.32042898],
       [0.86082189, 0.13917811],
       [0.16084394, 0.83915606],
       [0.59430082, 0.40569918],
       [0.59675531, 0.40324469],
       [0.75996029, 0.24003971],
       [0.59941268, 0.40058732],
       [0.

In [57]:
predicted_proba.shape

(140, 2)

In [61]:
predicted_proba[:,1]

array([0.17042874, 0.14836002, 0.20220417, 0.406788  , 0.42634133,
       0.91958176, 0.32404871, 0.64431579, 0.2836797 , 0.25994824,
       0.13543365, 0.32507268, 0.73429413, 0.55074255, 0.27399638,
       0.5078183 , 0.10540405, 0.78558388, 0.13296527, 0.41598341,
       0.26973425, 0.25588215, 0.31821401, 0.32042898, 0.13917811,
       0.83915606, 0.40569918, 0.40324469, 0.24003971, 0.40058732,
       0.11740629, 0.14127068, 0.59939433, 0.56123137, 0.27824269,
       0.64991631, 0.31821401, 0.13371416, 0.85473685, 0.19918143,
       0.518433  , 0.25185802, 0.63451971, 0.12814276, 0.2248817 ,
       0.72597901, 0.76889861, 0.88389353, 0.30906773, 0.13053509,
       0.25994824, 0.31362277, 0.42634133, 0.93283814, 0.13871298,
       0.2248817 , 0.97636259, 0.27824269, 0.87185363, 0.22500107,
       0.59270754, 0.11962568, 0.49902329, 0.64431579, 0.13543365,
       0.41351   , 0.68000722, 0.05803086, 0.26979066, 0.50509959,
       0.25994824, 0.24003971, 0.69828514, 0.31362277, 0.13416

In [62]:
#save the models
import pickle

In [65]:
with open('../model/model', 'wb') as file:
    pickle.dump(reg, file)

In [66]:
# pickle the scaler file
with open('../model/scaler','wb') as file:
    pickle.dump(scalar, file)